s=input("enter a string:")
print("orginal string:",s)
print("length:",len(s))
print("upper case:",s.upper())
print("lower case:",s.lower())
print("capitalized:",s.capitalize())
print("IS alphabatic:",s.isalpha())
print("IS numeric:",s.isdigit())
print("replace with @:",s.replace('a','@'))
print("postion:",s.find('a'))
