a=int(input("enter first number:"))
b=int(input("enter second number:"))
c=int(input("enter third number:"))
maximum=max(a,b,c)
minimum=min(a,b,c)
print("maximum=:",maximum)
print("minimum=:",minimum)
