import numpy as np
arr=np.array([10,20,30,40,50])
print("enter array:",arr)
print("enter first element:",arr[0])
print("enter second element:",arr[-1])
print("sum",np.sum(arr))
print("minimum",np.min(arr))
print("maximum",np.max(arr))
print("mean:",np.mean(arr))
print("standard deviation",np.std(arr))
print("shape",arr.shape)
print("size",arr.size)
print("add 5 for each element",arr+5)
print("multiply 2 for each element",arr*2)
