import numpy as np
arr= np.array([[1, 2],
              [3, 4]])
print("\n2D arrray:")
print(arr)
print("\ntranspose:")
print(arr.T)
print("sum:",np.sum(arr))
print("minimum:",np.min(arr))
print("maximum:",np.max(arr))
print("mean:",np.mean(arr))
print("standard deviation:",np.std(arr))
print("shape:",arr.shape)
print("size:",arr.size)
print("Reshaped (2x2):")
print(arr.reshape(2,2))
print("\n sort:")
print(np.sort(arr))
print("row sum:",np.sum(arr,axis=0))
print("coloumn:",np.sum(arr,axis=1))
